package com.zerodeplibs.webpush.ext.jwt.jjwt;

import com.zerodeplibs.webpush.jwt.VAPIDJWTGenerator;
import com.zerodeplibs.webpush.jwt.VAPIDJWTGeneratorFactory;
import java.security.interfaces.ECPrivateKey;
import java.security.interfaces.ECPublicKey;

/**
 * The factory class for {@link VAPIDJWTGenerator}.
 * {@link VAPIDJWTGenerator}s generated by this class utilizes <a href="https://github.com/jwtk/jjwt">Java JWT</a>.
 *
 * @author Tomoki Sato
 */
public class JavaJwtVAPIDJWTGeneratorFactory implements VAPIDJWTGeneratorFactory {
    @Override
    public VAPIDJWTGenerator create(ECPrivateKey privateKey,
                                    ECPublicKey publicKey) {
        return new JavaJwtVAPIDJWTGenerator(privateKey);
    }
}
