changelog:
    categories:
        - title: 🛠 Breaking Changes
          labels:
              - breaking-change
        - title: 💪 Enhancement
          labels:
              - enhancement
        - title: 🐝 Bug fixes
          labels:
              - bug
        - title: 📝 Documentation
          labels:
              - documentation
        - title: 👒 Dependencies
          labels:
              - dependencies-for-release
        - title: Others
          labels:
              - '*'
          exclude:
              labels:
                  - dependencies

