package com.zerodeplibs.webpush.ext.jwt.auth0;

import com.zerodeplibs.webpush.jwt.VAPIDJWTGenerator;
import com.zerodeplibs.webpush.jwt.VAPIDJWTGeneratorFactory;
import java.security.interfaces.ECPrivateKey;
import java.security.interfaces.ECPublicKey;

/**
 * The factory class for {@link VAPIDJWTGenerator}.
 * {@link VAPIDJWTGenerator}s generated by this class utilizes <a href="https://github.com/auth0/java-jwt">Java JWT - auth0</a>.
 *
 * @author Tomoki Sato
 */
public class Auth0VAPIDJWTGeneratorFactory implements VAPIDJWTGeneratorFactory {

    @Override
    public VAPIDJWTGenerator create(
        ECPrivateKey privateKey,
        ECPublicKey publicKey) {
        return new Auth0VAPIDJWTGenerator(privateKey, publicKey);
    }
}
