package com.zerodeplibs.webpush.ext.jwt.jose4j;

import com.zerodeplibs.webpush.jwt.VAPIDJWTGenerator;
import com.zerodeplibs.webpush.jwt.VAPIDJWTGeneratorFactory;
import java.security.interfaces.ECPrivateKey;
import java.security.interfaces.ECPublicKey;

/**
 * The factory class for {@link VAPIDJWTGenerator}.
 * {@link VAPIDJWTGenerator}s generated by this class utilizes <a href="https://bitbucket.org/b_c/jose4j/wiki/Home">jose4j</a>.
 *
 * @author Tomoki Sato
 */
public class Jose4jVAPIDJWTGeneratorFactory implements VAPIDJWTGeneratorFactory {
    @Override
    public VAPIDJWTGenerator create(
        ECPrivateKey privateKey,
        ECPublicKey publicKey) {
        return new Jose4jVAPIDJWTGenerator(privateKey);
    }
}
