package com.zerodeplibs.webpush.ext.jwt.fusionauth;

import com.zerodeplibs.webpush.jwt.VAPIDJWTGenerator;
import com.zerodeplibs.webpush.jwt.VAPIDJWTGeneratorFactory;
import java.security.interfaces.ECPrivateKey;
import java.security.interfaces.ECPublicKey;

/**
 * The factory class for {@link VAPIDJWTGenerator}.
 * {@link VAPIDJWTGenerator}s generated by this class utilizes <a href="https://github.com/fusionauth/fusionauth-jwt">FusionAuth JWT</a>.
 *
 * @author Tomoki Sato
 */
public class FusionAuthVAPIDJWTGeneratorFactory implements VAPIDJWTGeneratorFactory {

    @Override
    public VAPIDJWTGenerator create(ECPrivateKey privateKey,
                                    ECPublicKey publicKey) {
        return new FusionAuthVAPIDJWTGenerator(privateKey);
    }
}
