name: Unit Test.
on:
    push:
        branches: [ dev ]
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
            - name: Set Up JDK
              uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
              with:
                  java-version: '17'
                  distribution: 'corretto'

            - name: Unit Test Core
              run:
                  sh ./scripts/test-core.sh

            - name: Unit Test Ext
              run:
                  sh ./scripts/test-ext.sh
