name: Unit Test.
on:
    push:
        branches: [ dev ]
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
            - name: Set Up JDK
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
              with:
                  java-version: '17'
                  distribution: 'corretto'

            - name: Unit Test Core
              run:
                  sh ./scripts/test-core.sh

            - name: Unit Test Ext
              run:
                  sh ./scripts/test-ext.sh
